// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package model

import (
	"database/sql"
)

type PressHistory struct {
	ID            int32
	UserID        sql.NullInt64
	UnixTimestamp sql.NullInt64
}

type Reward struct {
	ID     int32
	UserID sql.NullInt64
	Reward sql.NullInt64
}

type User struct {
	ID       int32
	Username sql.NullString
}
